### ISSUE TITLE
[Rest API]: Per request actor model

### ISSUE THREAD

**Issue by Aranir** [reminisceme/crawler#2]
At the moment the [ask][ask_link] patern of akka is used, which will yield sub optimal performance and makes the testing more cumbersome.

It would be best if we would implement a per request actor model similar to this [article][per-request_link].

[ask_link]: http://doc.akka.io/docs/akka/snapshot/scala/actors.html
[per-request_link]:http://techblog.net-a-porter.com/2013/12/ask-tell-and-per-request-actors/

**Comment by pirroh** [comment]
@Aranir: correct me if I'm wrong, but this issue can be closed now, right?
