### ISSUE TITLE
[Questions]:Who liked this picture?

### ISSUE THREAD

**Issue by Aranir** [reminisceme/crawler#3]
The FB API doesn't allow any querying for a pictures which have likes (as far as I could find out, but I would be happy to be educated on this matter).

This means for this question we need to hunt for a picture which has likes, depending on how many picture the person uploaded without any likes this could take quiet a while and require a many API calls.

And additionally this question most likely would also need to have access to the friends list (which is still uncertain we will obtain).

Any other thoughts or help on this?

**Comment by pirroh** [comment]
Things changed quite a bit from what we discussed in this issue.
@Aranir: can you transfer the core insights of the semester report in a few wiki pages? At this point it starts to be useful to document the high-level design choices.

**Comment by Aranir** [comment]
Indeed, I updated the wiki and the main readme to reflect the changes we made.

@pirroh is it sufficiently clear or should we go into more detail?

**Comment by pirroh** [comment]
@Aranir: looks great, closing this issue!
