### ISSUE TITLE
Document how to set up the app

### ISSUE THREAD

**Issue by romac** [reminisceme/crawler#5]
It would be awesome if you could document how to set up the app and its dependencies (if any) in the README (or some other doc in the repository).

**Comment by Aranir** [comment]
Added a description for the installation and the required env. variables to be used.

Any suggestions to improve it?

**Comment by romac** [comment]
There's everything needed, thanks :)

Only issue now is that we don't have enough RAM on the droplet to launch sbt (same problem with `game-creator`): 

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000b0000000, 357892096, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 357892096 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /var/apps/crawler/hs_err_pid8021.log
```

I'll try to `assemble` the JAR locally and only run it on the host but I'm not hopeful. I'll upgrade the droplet to 1GB RAM (let's hope it's gonna be enough for both `crawler` and `game-creator`).
